### ISSUE TITLE
How to create a client?

### ISSUE THREAD

**Issue by Dazmed707** [romainvg/OCRP6#5]
How to create a client?
and what archive edit for rat status listening in port "xxxx" and edit archive for ip and port in client?

**Comment by AN-Mantis** [comment]
![image](https://user-images.githubusercontent.com/73964712/108347758-31156c80-71e1-11eb-94a0-a92a37a09cc8.png)

**Comment by Dazmed707** [comment]
and where do I put the port number?
and how do I convert to .exe?

**Comment by romainvg** [comment]
Dear Dazmed,

I Invite you to run the RemoteAdminTool.py on your desktop.

Then you have to run the AgentClient.py on the  remote host/server(s) you
need to control / manage or whatever.

If you need to converts .py to .exe you can use this useful tool : pip
install auto-py-to-exe

You can change the socket port on the AgentClient.py( port = 8085 # socket
server port number )
